### ISSUE TITLE
Calculate the mean in the transmittance domain rather than CIELAB

### ISSUE THREAD

**Issue by waynewccheng** [waynewccheng/andrewcode#1]
https://github.com/waynewccheng/andrewcode/blob/7dbc76e456be9271343d88b7534ea26e85e4292e/AndrewMatlabDetail/TissueMeasurements/f_processdata_roi.m#L77

**Comment by andrew-lamont** [comment]
To address this, I've broken the pixel uniformity assessment and the dE calculation into two different functions

**Comment by waynewccheng** [comment]
OK
